Project Pace {
  database_type: 'PostgreSQL'
  Note: '''
  # Pace
  **Testing DBDoc\'s program

  '''
}

Table activitycode [headercolor: #27ae60, note: 'PACE entity'] {
  jcmasteid varchar PK
  jcdescription varchar
  jccostcenterid varchar
}
Table costcenter [headercolor: #27ae60, note: 'PACE entity'] {
  jccostcenterid varchar PK
  jcdescription varchar
  jcdeptid varchar(3)
}
Table activityrate [headercolor: #27ae60, note: 'PACE entity'] {
  id int PK
  activitycode varchar
  linenumber int
  machinecost numeric
  laborcost numeric
  laboroverhead numeric
  generaloa numeric
}
Table department [headercolor: #27ae60, note: 'PACE entity'] {
  jcdeptid varchar PK
  jcdeptdescription varchar
}
Table jobplan [headercolor: #27ae60, note: 'PACE entity'] {
  id int PK
  job varchar
  part varchar
  activitycode varchar
  status int
}
Table jobpart [headercolor: #27ae60, note: 'PACE entity'] {
  ccjobpart varchar PK
  ccmasterid varchar PK
}
Table job [headercolor: #27ae60, note: 'PACE entity'] {
  ccjobpart varchar PK
  ccmasterid varchar pK
}

Table u_jobpart [headercolor: #27ae60, note: 'PACE entity'] {
  ccjobpart varchar PK
  ccmasterid varchar PK
  u_collaterateid varchar
  u_collateratejob varchar
  u_kit int
}
Table udo_kit [headercolor: #27ae60, note: 'PACE entity'] {
  id int PK
  description varchar
  status varchar
}

tablegroup pace {
  activitycode
  costcenter
  department
  activityrate
  u_jobpart
  job
  udo_kit
}


Ref: "activitycode"."jccostcenterid" < "costcenter"."jccostcenterid"

Ref: "activityrate"."activitycode" < "activitycode"."jcmasteid"

Ref: "costcenter"."jcdeptid" < "department"."jcdeptid"

Ref: "jobplan"."activitycode" < "activitycode"."jcmasteid"

Ref: "jobplan"."job" < "jobpart"."ccmasterid"

Ref: "jobplan"."part" < "jobpart"."ccjobpart"

Ref: "order_items"."id" < "u_jobpart"."u_collaterateid"

Ref: "u_jobpart"."ccjobpart" < "jobpart"."ccjobpart"

Ref: "u_jobpart"."ccmasterid" < "jobpart"."ccmasterid"

Ref: "u_jobpart"."ccmasterid" < "job"."ccmasterid"

Ref: "u_jobpart"."u_kit" < "udo_kit"."id"